# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-23 12:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_auto_20170523_1924'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentreply',
            old_name='author',
            new_name='user',
        ),
        migrations.AddField(
            model_name='commentreply',
            name='email',
            field=models.EmailField(blank=True, max_length=50, null=True, verbose_name='邮箱地址'),
        ),
    ]
