# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-23 15:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0004_auto_20170523_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentreply',
            name='nickname',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='用户昵称'),
        ),
    ]
