# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-24 10:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0005_commentreply_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentreply',
            name='date_reply',
            field=models.DateTimeField(auto_now_add=True, default='2017-05-24 18:40:34.354804', verbose_name='回复评论时间'),
            preserve_default=False,
        ),
    ]
