# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-24 10:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0006_commentreply_date_reply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentreply',
            name='to',
        ),
        migrations.AddField(
            model_name='commentreply',
            name='reply_to',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='回复的用户昵称'),
        ),
    ]
