# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-27 07:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0008_auto_20170524_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentreply',
            name='comment_child',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='回复了哪条子评论'),
        ),
    ]
