# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-27 09:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0009_commentreply_comment_child'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentreply',
            name='article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Blog.Article', verbose_name='文章'),
        ),
    ]
