# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-04 04:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0011_remove_commentreply_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='avatar',
            field=models.ImageField(blank=True, default='avatar/default.png', max_length=200, null=True, upload_to='', verbose_name='用户头像'),
        ),
        migrations.AddField(
            model_name='commentreply',
            name='avatar',
            field=models.ImageField(blank=True, default='avatar/default.png', max_length=200, null=True, upload_to='', verbose_name='用户头像'),
        ),
    ]
