# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-04 06:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0012_auto_20170604_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='avatar',
            field=models.ImageField(blank=True, default='uploads/avatar/default.png', max_length=200, null=True, upload_to='', verbose_name='用户头像'),
        ),
        migrations.AlterField(
            model_name='commentreply',
            name='avatar',
            field=models.ImageField(blank=True, default='uploads/avatar/default.png', max_length=200, null=True, upload_to='', verbose_name='用户头像'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='uploads/avatar/default.png', max_length=200, null=True, upload_to='avatar', verbose_name='用户头像'),
        ),
    ]
