# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-11 10:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0013_auto_20170604_1415'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clickings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_ip', models.CharField(max_length=20, verbose_name='用户IP地址')),
                ('click_date', models.DateTimeField(auto_now_add=True, verbose_name='点击时间')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Blog.Article', verbose_name='文章')),
            ],
        ),
    ]
