# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-11 14:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0014_clickings'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPraises',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_praise', models.CharField(max_length=10, verbose_name='累计总数')),
                ('user_ip', models.CharField(max_length=20, verbose_name='用户IP地址')),
                ('click_date', models.DateTimeField(auto_now_add=True, verbose_name='点击时间')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Blog.Article', verbose_name='文章')),
            ],
        ),
        migrations.RemoveField(
            model_name='clickings',
            name='article',
        ),
        migrations.DeleteModel(
            name='Clickings',
        ),
    ]
