# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-11 15:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0018_auto_20170611_2344'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='pra',
            new_name='praise_count',
        ),
    ]
