# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-11 16:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0020_auto_20170611_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpraises',
            name='praise_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='点击时间'),
        ),
    ]
